name: GitHub CI

on: 
  push:
    branches: [ master ]
    tags:
      - '**'
  workflow_dispatch:
  pull_request:

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base
        uses: actions/checkout@v4
      
      - name: Add commit id into version
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          SHA=$(git rev-parse --short HEAD)
          sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
      
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y bash git nodejs npm
          chmod +x scripts/build.alpine.release.sh
          ./scripts/build.alpine.release.sh
      
      - name: Package Release
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          zip -r subconverter_linux64.zip subconverter/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: subconverter_linux64.zip
          path: subconverter_linux64.zip
      
      - name: Draft Release
        if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: subconverter_linux64.zip
          draft: true
